// Generated by scripts/bundle-migrations.ts from drizzle/. Do not edit.
export const MIGRATIONS: ReadonlyArray<{
	name: string
	statements: readonly string[]
}> = [
	{
		"name": "0000_fluffy_sabretooth.sql",
		"statements": [
			"CREATE TABLE `deployment_config` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`encrypted` integer DEFAULT false NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
			"CREATE TABLE `member` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`organization_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`role` text DEFAULT 'member' NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);",
			"CREATE UNIQUE INDEX `uniq_member_org_user` ON `member` (`organization_id`,`user_id`);",
			"CREATE INDEX `idx_member_org_id` ON `member` (`organization_id`);",
			"CREATE INDEX `idx_member_user_id` ON `member` (`user_id`);",
			"CREATE TABLE `organization` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`logo` text,\n\t`metadata` text,\n\t`created_at` integer NOT NULL\n);",
			"CREATE TABLE `organization_settings` (\n\t`org_id` text PRIMARY KEY NOT NULL,\n\t`brain_proactivity` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`org_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade\n);",
			"CREATE TABLE `user` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text DEFAULT '' NOT NULL,\n\t`email` text NOT NULL,\n\t`image` text,\n\t`deleted` integer DEFAULT false NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
			"CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);",
			"CREATE TABLE `google_workspace_grant` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`google_sub` text NOT NULL,\n\t`email` text NOT NULL,\n\t`oauth_client_id` text NOT NULL,\n\t`access_token_enc` text NOT NULL,\n\t`refresh_token_enc` text,\n\t`expires_at` integer,\n\t`scopes` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`last_error` text,\n\t`refresh_version` integer DEFAULT 0 NOT NULL,\n\t`refresh_claim_token` text,\n\t`refresh_claim_expires_at` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);",
			"CREATE UNIQUE INDEX `uniq_google_workspace_grant_identity` ON `google_workspace_grant` (`user_id`,`google_sub`,`oauth_client_id`);",
			"CREATE INDEX `idx_google_workspace_grant_user` ON `google_workspace_grant` (`user_id`);",
			"CREATE TABLE `mcp_connection` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`org_id` text NOT NULL,\n\t`user_id` text,\n\t`runtime` text DEFAULT 'remote_mcp' NOT NULL,\n\t`server_slug` text NOT NULL,\n\t`server_url` text,\n\t`google_workspace_grant_id` text,\n\t`transport` text DEFAULT 'http' NOT NULL,\n\t`auth_type` text NOT NULL,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`access_token` text,\n\t`refresh_token` text,\n\t`expires_at` integer,\n\t`scopes` text,\n\t`metadata` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`org_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`google_workspace_grant_id`) REFERENCES `google_workspace_grant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
			"CREATE INDEX `idx_mcp_connection_org_id` ON `mcp_connection` (`org_id`);",
			"CREATE INDEX `idx_mcp_connection_status` ON `mcp_connection` (`status`);",
			"CREATE UNIQUE INDEX `uniq_mcp_connection_org_slug_user` ON `mcp_connection` (`org_id`,`server_slug`,`user_id`) WHERE \"mcp_connection\".\"user_id\" is not null;",
			"CREATE UNIQUE INDEX `uniq_mcp_connection_org_slug_shared` ON `mcp_connection` (`org_id`,`server_slug`) WHERE \"mcp_connection\".\"user_id\" is null;",
			"CREATE TABLE `mcp_oauth_state` (\n\t`state_token` text PRIMARY KEY NOT NULL,\n\t`org_id` text NOT NULL,\n\t`user_id` text,\n\t`runtime` text DEFAULT 'remote_mcp' NOT NULL,\n\t`server_slug` text NOT NULL,\n\t`server_url` text,\n\t`code_verifier` text,\n\t`pkce_verifier_enc` text,\n\t`requested_scopes` text,\n\t`target_google_workspace_grant_id` text,\n\t`client_info` text,\n\t`tokens` text,\n\t`redirect_url` text,\n\t`context` text,\n\t`expires_at` integer,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`org_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`target_google_workspace_grant_id`) REFERENCES `google_workspace_grant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
			"CREATE INDEX `idx_mcp_oauth_state_expires_at` ON `mcp_oauth_state` (`expires_at`);",
			"CREATE TABLE `slack_account_link_state` (\n\t`token_hash` text PRIMARY KEY NOT NULL,\n\t`team_id` text NOT NULL,\n\t`slack_user_id` text NOT NULL,\n\t`org_id` text NOT NULL,\n\t`slack_email` text,\n\t`slack_display_name` text,\n\t`expires_at` integer NOT NULL,\n\t`consumed_at` integer,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`team_id`) REFERENCES `slack_workspace`(`team_id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`org_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade\n);",
			"CREATE INDEX `idx_slack_account_link_state_expires_at` ON `slack_account_link_state` (`expires_at`);",
			"CREATE INDEX `idx_slack_account_link_state_identity` ON `slack_account_link_state` (`team_id`,`slack_user_id`);",
			"CREATE TABLE `slack_workspace` (\n\t`team_id` text PRIMARY KEY NOT NULL,\n\t`org_id` text NOT NULL,\n\t`bot_user_id` text,\n\t`bot_token_enc` text NOT NULL,\n\t`team_name` text,\n\t`installed_by_user_id` text,\n\t`scopes` text,\n\t`app_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`org_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`installed_by_user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null\n);",
			"CREATE INDEX `idx_slack_workspace_org_id` ON `slack_workspace` (`org_id`);",
			"CREATE TABLE `slack_workspace_member` (\n\t`team_id` text NOT NULL,\n\t`slack_user_id` text NOT NULL,\n\t`org_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`email` text,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`link_source` text DEFAULT 'email_match' NOT NULL,\n\t`provisioned_member_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tPRIMARY KEY(`team_id`, `slack_user_id`),\n\tFOREIGN KEY (`team_id`) REFERENCES `slack_workspace`(`team_id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`org_id`) REFERENCES `organization`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`provisioned_member_id`) REFERENCES `member`(`id`) ON UPDATE no action ON DELETE set null\n);",
			"CREATE INDEX `idx_slack_workspace_member_org_id` ON `slack_workspace_member` (`org_id`);",
			"CREATE INDEX `idx_slack_workspace_member_user_id` ON `slack_workspace_member` (`user_id`);"
		]
	}
]
