/**
 * Bundle drizzle/*.sql into src/db/migrations.generated.ts, so the worker can
 * apply its own migrations. Run after `drizzle-kit generate` (db:generate does).
 */
const root = `${import.meta.dir}/..`
const journal = (await Bun.file(`${root}/drizzle/meta/_journal.json`).json()) as {
	entries: Array<{ tag: string }>
}

const migrations = await Promise.all(
	journal.entries.map(async ({ tag }) => {
		const sql = await Bun.file(`${root}/drizzle/${tag}.sql`).text()
		return {
			// Wrangler records applied migrations by file name; so do we.
			name: `${tag}.sql`,
			statements: sql
				.split("--> statement-breakpoint")
				.map((statement) => statement.trim())
				.filter(Boolean),
		}
	}),
)

await Bun.write(
	`${root}/src/db/migrations.generated.ts`,
	`// Generated by scripts/bundle-migrations.ts from drizzle/. Do not edit.
export const MIGRATIONS: ReadonlyArray<{
	name: string
	statements: readonly string[]
}> = ${JSON.stringify(migrations, null, "\t")}
`,
)
console.log(`bundled ${migrations.length} migration(s)`)
